version: 0.0
os: linux
  
hooks:
  AfterInstall:
    - location: scripts/start
      timeout: 300
      runas: root
      
  ApplicationStop:
    - location: scripts/stop
      timeout: 300
      runas: root
