version: 0.2

env:
  parameter-store:
    USERNAME: myapp-docker-credentials-username
    PASSWORD: myapp-docker-credentials-password
    KEY:  1.1

        
phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - node --version
      - echo "installed node "
    # steps:
  pre_build:
    commands:
      - npm install
      - echo "dependencies installed"
  build:
    commands:
      #- docker build . -t inderharrysingh/netflix-react-app:latest --build-arg TMDB_V3_API_KEY=$KEY
       docker build . -t $USERNAME/netflix-react-app:latest
  post_build:
    commands:
      - echo "waiting right now"
      - echo "$PASSWORD" | docker login -u $USERNAME -p --password-stdin
      - docker push $USERNAME/netflix-react-app:latest
artifacts:
  files:
    - '**/*'
  base-directory: "./"
  name: build-artifact-name
  discard-paths: no
